version: '3.9'

services:

  db:
    image: postgres
    volumes:
      - /private/var/lib/postgresql:/var/lib/postgresql
    ports:
      - "${DOCKER_DB_PORT}:5432"
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}

  adminer:
    image: adminer
    depends_on: 
      - db
    ports:
      - ${DOCKER_ADMINER_PORT}:8080